name: Build DNSCrypt Proxy
on:
  workflow_dispatch:
  schedule:
    # The "*" (#42, asterisk) character has special semantics in YAML, so this
    # string has to be quoted.
    - cron: '0 0 * * *'
jobs:
  fetch-tags:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0

      - uses: actions/setup-node@v2
        with:
          cache: 'npm'
          node-version: lts/*

      - run: npm install

      - name: Fetch Tags
        run: ./node_modules/.bin/ts-node build.ts "DNSCrypt" "dnscrypt-proxy" "linux_x86_64"

      - id: set-matrix
        run: echo "::set-output name=matrix::$(cat ${GITHUB_WORKSPACE}/matrix.json)"

  build:
    needs: fetch-tags
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.fetch-tags.outputs.matrix)}}
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
      - run: mkdir ctx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-dnscrypt-proxy-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-dnscrypt-proxy-buildx-
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: yknx94
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./ctx
          file: ./Dockerfile
          build-args: |
            ASSET_URL=${{ matrix.asset }}
            BINARY_NAME=dnscrypt-proxy
          push: true
          tags: yknx94/dnscrypt-proxy:${{ matrix.tag }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
      - # Temp fix
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
        name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
